spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: ${TODO_SERVICE_PORT:8080}

# eventuali proprietà comuni (log, jackson, ecc.)
logging:
  level:
    root: INFO
