spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:exampledb}
    username: ${DB_USER:example_user}
    password: ${DB_PASSWORD:secret_password}

logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
