spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: ${TODO_SERVICE_PORT:8080}

jwt:
  secret: ${TODO_JWT_SECRET:defaultSecret}
  expiration: ${TODO_JWT_EXPIRATION:3600} # in seconds
# eventuali proprietà comuni (log, jackson, ecc.)
logging:
  level:
    root: INFO
