spring:
  profiles: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

# meno log in produzione
logging:
  level:
    root: WARN
    com.example.todo: INFO

# espongo solo health & info
management:
  endpoints:
    web:
      exposure:
        include: health,info
